CREATE TABLE USER4(
ID NUMBER NOT NULL PRIMARY KEY,
USER_NAME NVARCHAR2(200) NOT NULL ,
CONSTRAINT NAME_UNQ UNIQUE (USER_NAME),
USER_PASSWORD NVARCHAR2(200) NOT NULL,
COUNTRY NVARCHAR2(200) NOT NULL,
USER_TYPE NVARCHAR2(20) NOT NULL CHECK (USER_TYPE = 'ADMIN' OR USER_TYPE = 'USER'));

CREATE SEQUENCE USER_SEQ MINVALUE 1 MAXVALUE 1000 START WITH 1 INCREMENT BY 1;