CREATE TABLE ORDER4(
ID NUMBER NOT NULL PRIMARY KEY,
USER_ID NUMBER NULL,
CONSTRAINT USER_ORDER_FK FOREIGN KEY (USER_ID) REFERENCES USER4(ID),
ROOM_ID NUMBER NULL,
CONSTRAINT ROOM_ROOM_FK FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ID),
DATE_FROM DATE,
DATE_TO DATE,
MONEY_PAID NUMBER(*,2) NOT NULL);

CREATE SEQUENCE ORDER_SEQ MINVALUE 1 MAXVALUE 1000 START WITH 1 INCREMENT BY 1;

