CREATE TABLE HOTEL(
ID NUMBER,
CONSTRAINT HOTEL_PK PRIMARY KEY (ID),
HOTEL_NAME NVARCHAR2(200) NOT NULL,
COUNTRY NVARCHAR2(200) NOT NULL,
CITY NVARCHAR2(200) NOT NULL,
STREET NVARCHAR2(200) NOT NULL);

CREATE SEQUENCE HOTEL_SEQ MINVALUE 1 MAXVALUE 100 START WITH 1 INCREMENT BY 1;

